[project]
name = "python-rembgnew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "easygui>=0.98.3",
    "onnxruntime==1.19.0",
    "rembg>=2.0.59",
]
